name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install modules
        run: yarn install
      - name: Build project
        run: yarn build
      - name: Build story
        run: yarn build:story
      - name: Unit test
        run: yarn test:unit
      - name: e2e test
        run: yarn test:e2e
      - name: start puppeteer e2e
        run: yarn global add serve
      # - name: start app  
        # run: yarn start
      - name: run e2e  
        run: yarn e2e
      - name: lint code
        run: yarn lint
